name: ubuntu-calculator-app
version: 2.3
summary: Ubuntu Calculator app
description: The calculator app for all Ubuntu devices.
confinement: strict
grade: stable

apps:
    ubuntu-calculator-app:
        command: desktop-launch qmlscene --desktop_file_hint=unity8 $SNAP/usr/share/ubuntu-calculator-app/ubuntu-calculator-app.qml
        plugs: [opengl, platform, unity7]

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform

parts:
    ubuntu-calculator-app:
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
        source: .
        build-packages:
            - cmake
            - gettext
            - intltool
            - python3
            - qtbase5-dev
            - qtdeclarative5-dev
        stage-packages:
            - qtubuntu-desktop
        snap:
          - -usr/share/doc
          - -usr/include
        after: [desktop-ubuntu-app-platform]

    environment:
        source: snap/
        plugin: dump
